export enum SectionType {
    UNKNOWN,
    ABOUT,
    AUTOWALKS,
    DISPATCH,
    ELEVATORS,
    ESCALATORS,
    HOME,
    INSTALLATION,
    MODERNIZATION,
    SERVICE_MAINTENANCE,
    PORTFOLIO,
    // PRIVACY_POLICY,
    // SITE_POLICY,
    SUPPORT
}
