export enum SectionType {
    UNKNOWN,
    ABOUT,
    AUTOWALKS,
    DISPATCH,
    ELEVATORS,
    ESCALATORS,
    HOME,
    INSTALLATION,
    MAINTENANCE,
    MODERNIZATION,
    RECOMMENDATIONS,
    PORTFOLIO,
    SUPPORT
}
